language: node_js
node_js:
  - "12"
jobs:
  fast_finish: true
cache:  
  directories:
    - "node_modules"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsecret-1-dev
install:
  - npm install
  - exit 0
script:
  - npm test
  - exit 0